### PR TITLE
fix(FormItem): 修复FormItem不在Form中使用报错的问题(#3947)

### LINKED ISSUE #3947: 🐛 [Bug]: FormItem 不在 Form中使用的情况下报错。
### Version

3.27.0

### Vue Version

3.5.6

### Link to minimal reproduction

[演练场](https://opentiny.design/vue-playground?mode=pc&theme=os#3.27|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuLy8g5byV5YWlIEBvcGVudGlueS92dWUg57uE5Lu2XG5pbXBvcnQgeyBCdXR0b24sIExpbmsgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXG4gICAgVGlueUxpbms6IExpbmtcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgbXNnOiAnaGVsbG8gd29ybGQhJ1xuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxuICBoMXtcbiAgICBjb2xvcjojNWU3Y2UwO1xuICB9XG4gIC50aW55dnVle1xuICAgIGZvbnQtc2l6ZTogMTh4cDtcbiAgICAmLXBhZ2V7XG4gICAgICBjb2xvcjojNWU3Y2UwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiIsIiI6IntcImltcG9ydHNcIjp7XCJ2dWVcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS92dWUvMy40LjI3L2ZpbGVzL2Rpc3QvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIixcImVjaGFydHNcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9lY2hhcnRzLzUuNC4xL2ZpbGVzL2Rpc3QvZWNoYXJ0cy5lc20uanNcIixcIkB2dWUvY29tcGlsZXItc2ZjXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQHZ1ZS9jb21waWxlci1zZmMvMy40LjI3L2ZpbGVzL2Rpc3QvY29tcGlsZXItc2ZjLmVzbS1icm93c2VyLmpzXCIsXCJAb3BlbnRpbnkvdnVlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMjcvZmlsZXMvZGlzdDMvdGlueS12dWUtcGMubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4yNy9maWxlcy9kaXN0My90aW55LXZ1ZS1pY29uLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1sb2NhbGVcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4yNy9maWxlcy9kaXN0My90aW55LXZ1ZS1sb2NhbGUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWNvbW1vblwiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtcnVudGltZS8zLjI3L2ZpbGVzL2Rpc3QzL3RpbnktdnVlLWNvbW1vbi5tanNcIixcIkBvcGVudGlueS92dWUtZGlyZWN0aXZlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMjcvZmlsZXMvZGlzdDMvdGlueS12dWUtZGlyZWN0aXZlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1odWljaGFydHNcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4yNy9maWxlcy9kaXN0My90aW55LXZ1ZS1odWljaGFydHMubWpzXCIsXCJAb3BlbnRpbnkvdnVlLXRoZW1lL1wiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtdGhlbWUvMy4yNy9maWxlcy9cIixcIkBvcGVudGlueS92dWUtdGhlbWUtbW9iaWxlL1wiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtdGhlbWUtbW9iaWxlLzMuMjcvZmlsZXMvXCIsXCJAb3BlbnRpbnkvdnVlLXJlbmRlcmxlc3MvXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1yZW5kZXJsZXNzLzMuMjcvZmlsZXMvXCIsXCJzb3J0YWJsZWpzXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vc29ydGFibGVqcy8xLjE1LjAvZmlsZXMvbW9kdWxhci9zb3J0YWJsZS5lc20uanNcIn19IiwidHNjb25maWcuanNvbiI6IntcclxuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcclxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxyXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxyXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXHJcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcclxuICB9LFxyXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwidGFyZ2V0XCI6IDMuM1xyXG4gIH1cclxufVxyXG4iLCJiYXNpYy11c2FnZS52dWUiOiI8dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJkZW1vLWZvcm1cIj5cbiAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cIuWNlemAiVwiPlxuICAgICAgICA8dGlueS1yYWRpbyB2LW1vZGVsPVwiY3JlYXRlRGF0YS5zZXhcIiBsYWJlbD1cIjFcIj4g55S3IDwvdGlueS1yYWRpbz5cbiAgICAgICAgPHRpbnktcmFkaW8gdi1tb2RlbD1cImNyZWF0ZURhdGEuc2V4XCIgbGFiZWw9XCIyXCIgdGV4dD1cIuWls1wiPjwvdGlueS1yYWRpbz5cbiAgICAgIDwvdGlueS1mb3JtLWl0ZW0+XG4gICAgICA8dGlueS1mb3JtLWl0ZW0gbGFiZWw9XCLmlbDlrZdcIj5cbiAgICAgICAgPHRpbnktbnVtZXJpYyB2LW1vZGVsPVwiY3JlYXRlRGF0YS5xdWFudGl0eVwiPjwvdGlueS1udW1lcmljPlxuICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cIuaXpeacn1wiPlxuICAgICAgICA8dGlueS1kYXRlLXBpY2tlciB2LW1vZGVsPVwiY3JlYXRlRGF0YS5kYXRlcGlja2VyXCI+PC90aW55LWRhdGUtcGlja2VyPlxuICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cIuaXtumXtFwiPlxuICAgICAgICA8dGlueS1kcm9wLXRpbWVzIHYtbW9kZWw9XCJjcmVhdGVEYXRhLmRyb3BUaW1lc1wiPjwvdGlueS1kcm9wLXRpbWVzPlxuICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cIuaPkOekulwiPlxuICAgICAgICA8dGlueS10b29sdGlwIGVmZmVjdD1cImxpZ2h0XCIgY29udGVudD1cIlRpbnlVSSBGb3JtIERlbW9cIiBwbGFjZW1lbnQ9XCJyaWdodFwiPlxuICAgICAgICAgIDx0aW55LWlucHV0IHYtbW9kZWw9XCJjcmVhdGVEYXRhLmlucHV0XCI+PC90aW55LWlucHV0PlxuICAgICAgICA8L3RpbnktdG9vbHRpcD5cbiAgICAgIDwvdGlueS1mb3JtLWl0ZW0+XG4gICAgICA8dGlueS1mb3JtLWl0ZW0gbGFiZWw9XCLmlofmnKxcIj5cbiAgICAgICAgPHRpbnktaW5wdXQgdi1tb2RlbD1cImNyZWF0ZURhdGEudGV4dGFyZWFcIiB0eXBlPVwidGV4dGFyZWFcIiBtYXhsZW5ndGg9XCIxNVwiPiA8L3RpbnktaW5wdXQ+XG4gICAgICA8L3RpbnktZm9ybS1pdGVtPlxuICAgICAgPHRpbnktZm9ybS1pdGVtPlxuICAgICAgICA8dGlueS1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzdWJtaXRDbGlja1wiPiDmj5DkuqQgPC90aW55LWJ1dHRvbj5cbiAgICAgIDwvdGlueS1mb3JtLWl0ZW0+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHtcbiAgVGlueUZvcm0sXG4gIFRpbnlGb3JtSXRlbSxcbiAgVGlueU51bWVyaWMsXG4gIFRpbnlSYWRpbyxcbiAgVGlueURhdGVQaWNrZXIsXG4gIFRpbnlEcm9wVGltZXMsXG4gIFRpbnlUb29sdGlwLFxuICBUaW55SW5wdXQsXG4gIFRpbnlCdXR0b24sXG4gIFRpbnlNb2RhbFxufSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5jb25zdCBjcmVhdGVEYXRhID0gcmVhY3RpdmUoe1xuICBxdWFudGl0eTogMCxcbiAgc2V4OiAnMScsXG4gIGRhdGVwaWNrZXI6ICcnLFxuICB0ZXh0YXJlYTogJycsXG4gIGRyb3BUaW1lczogJycsXG4gIGlucHV0OiAnJ1xufSlcblxuZnVuY3Rpb24gc3VibWl0Q2xpY2soKSB7XG4gIFRpbnlNb2RhbC5hbGVydCgn5o+Q5LqkJylcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmRlbW8tZm9ybSB7XG4gIHdpZHRoOiAzODBweDtcbn1cbjwvc3R5bGU+XG4iLCJfbyI6e319)

### Step to reproduce

直接进入

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

Formily Tiny Vue

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by neostfox**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3947 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved form component stability by making it resilient to missing form context: guarded accesses, safe fallbacks for label/size/tooltip/display-only/disabled behaviors, and updated defaults to avoid runtime errors when a form instance is absent.
  * Adjusted internal state typing to allow an absent form instance without changing public APIs.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/renderless/src/form-item/vue.ts [hunk 1]
```diff
@@ -105,22 +105,28 @@ const initState = ({
...
     isErrorBlock: computed(() => api.computedIsErrorBlock()),
-    disabled: computed(() => state.formInstance.disabled || props.disabled),
-    tooltipType: computed(() => state.formInstance.state.tooltipType),
+    /**
+     * TODO: There is a potential issue here. Need to confirm whether to keep this logic.
+     * There does not have disabled prop in form-item, but disabled is used here, I think it is a mistake.
+     * If not, need to add disabled prop in form-item component.
+     */
+    // @ts-expect-error Need to confirm whether to keep this logic
+    disabled: computed(() => state.formInstance?.disabled || props.disabled),
```
Comment (neostfox) [inline packages/renderless/src/form-item/vue.ts:128]: 我们需要讨论一下 props.disabled。
在 vue 的  属性中没有发现 disabled。
1、如果要支持，我们需要增加声明。
2、如果不需要支持我们就需要移除。
无论如何都应该在另外一个 PR 中来解决这个问题。

**Review by neostfox — COMMENTED** [review]
关于 FormItem 的 disabled 需要讨论

File: packages/renderless/src/form-item/vue.ts (hunk 1 above)
Comment (kagol) [reply packages/renderless/src/form-item/vue.ts:128]: @neostfox TinyVue 组件库支持自定义多套模板，`form-item` 有 `pc`/`mobile-first` 两套模板，两套模板共同同一份 renderless 逻辑，`mobile-first` 模板中使用了 `disabled`，所以这块逻辑还是不可以移除的。

https://github.com/opentiny/tiny-vue/blob/ec6d4b59d0e0051310d0e316676956a9d939eb25/packages/vue/src/form-item/src/mobile-first.vue#L192

**Review by kagol — APPROVED** [review]
