### PR TITLE
fix(timeline): add description prop for configuration mode display Fixes #3070

### LINKED ISSUE #3070: 🐛 [Bug]: Timeline 配置式，description 字段配置了无法展示
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

无

### Step to reproduce

无

### What is expected

Timeline 配置式，description 字段配置了无法展示

### What is actually happening

Timeline 配置式，description 字段配置了无法展示

### What is your project name

无

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by IKEYCY**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Summary by CodeRabbit

* **New Features**
  * Added a public `description` property to the timeline component, enabling customizable item descriptions across PC and mobile-first views.
  * Timeline items now display the `description` property when provided, falling back to existing item content otherwise.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by zzcr** [comment]
您好，感谢您的PR，这个PR提交是为了解决什么样的场景问题呢？能不能描述一下呢？

**Comment by IKEYCY** [comment]
你好，这个改动主要是为了解决描述文本数据来源单一的问题。现在组件只能从 node 对象里取 description 字段，但实际项目中描述文本可能来自不同地方，有些接口返回的字段名不是&nbsp;description，可能是&nbsp;desc、content等
<!-- 之前只能这样用 --&gt;
<timeline-item :node="{ description: '文本' }" /&gt;


<!-- 现在可以更灵活 --&gt;
<timeline-item description="直接传入文本" /&gt;
<timeline-item :description="动态变量" /&gt;
<timeline-item :node="原有方式继续支持" /&gt;

其他UI框架类似设计的例子：Element UI​ 的Steps 组件中有类似思路，Ant Design Vue​ 的 Timeline 组件也采用类似模式，这些主流框架都遵循"属性配置 + 插槽自定义"的组合模式，这样既保持了向后兼容，又提供了更便捷的数据传入方式





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年11月20日(星期四) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] fix(timeline): add description prop for configuration mode display Fixes #3070 (PR #3822)



Issues-translate-bot left a comment (opentiny/tiny-vue#3822)
  
Bot detected the issue body's language is not English, translate it automatically.
  
 
Hello, thank you for your PR. What kind of scenario problem is this PR submitted to solve? Can you describe it?

File: examples/sites/demos/apis/time-line.js [hunk 1]
```diff
@@ -244,6 +244,17 @@ export default {
...
           mfDemo: ''
+        },
+        {
+          name: 'description',
+          type: 'string',
+          defaultValue: '',
+          desc: {
+            'zh-CN': '时间线描述',
+            'en-US': 'Timeline description'
+          },
```
Comment (zzcr) [inline examples/sites/demos/apis/time-line.js:255]: 加上配置项表示整个特性是3.28.0版本添加的哈：meta: {
            stable: '3.28.0'
          }
