### PR TITLE
fix(breadcrumb): [breadcrumb] update size prop type and add validator

### LINKED ISSUE #3004: 🐛 [Bug]: 文档中 Breadcrumb 及 BreadcrumbItem size 属性应当为枚举，目前为 string
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

无

### Step to reproduce

无

### What is expected

文档中 Breadcrumb 及 BreadcrumbItem size 属性应当为枚举，目前为 string

### What is actually happening

文档中 Breadcrumb 及 BreadcrumbItem size 属性应当为枚举，目前为 string

### What is your project name

无

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by gweesin**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3004 

## What is the new behavior?

validate size property

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Refactor**
  - Improved size validation for breadcrumb and breadcrumb-item components to enforce consistent and allowed values.
  - Restricted sizing options to ensure uniform appearance across the components.

### CODE REVIEW

**Review by zzcr — APPROVED** [review]

File: packages/vue/src/breadcrumb-item/src/index.ts [hunk 1]
```diff
@@ -19,7 +19,11 @@ export const breadcrumbItemProps = {
     type: Boolean,
     default: false
   },
-  size: String,
+  size: {
+    type: String,
+    default: '',
+    validator: (val: string) => [/* 'large', */ 'medium', /* 'small', 'mini',  */ ''].includes(val)
```
Comment (zzcr) [inline packages/vue/src/breadcrumb-item/src/index.ts:25]: 目前仅支持medium，那large这些打上注释的目的是什么呢？

Comment (gweesin) [reply packages/vue/src/breadcrumb-item/src/index.ts:25]: 不确定后续是否需要支持，可以先删除

Comment (zzcr) [reply packages/vue/src/breadcrumb-item/src/index.ts:25]: 可以先删除，后续有需要再添加哈
