### PR TITLE
fix(tree-select): [tree-select] fix tree-select can't load data dynamically close #2287

### LINKED ISSUE #2287: 🐛 [Bug]: treeSelect动态加载问题
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue

### Step to reproduce

页面上使用treeSelect组件
image
在组件tree-op中，绑定数值

在ts中定义数值，如果直接定义数值，则可以直接在页面上显示，如下两幅图所示
image
image
但是如果定义是赋空，在后续onMounted中，给定义的数值赋值，则组件中无数据，无法动态加载
image
image
image

### What is expected

显示动态加载的数据在下拉框中

### What is actually happening

仅初次定义的数据可以被加载中树形结构中，后续的动态更新的并不能加载进入下拉列表

### What is your project name

Emp

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by kagol**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #2287 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced reactivity in the tree select component by adding a watch functionality that updates the tree data automatically when changes occur.

- **Bug Fixes**
	- Improved handling of nested data changes within the tree data structure, ensuring accurate updates.

### CODE REVIEW

File: packages/renderless/src/tree-select/vue.ts [hunk 1]
```diff
@@ -17,5 +17,11 @@ export const renderless = (props, { reactive, computed }, { vm, emit }) => {
     check: check({ props, vm, emit })
   })
 
+  watch(
+    () => props.treeOp.data,
+    (data) => data && (state.treeData = data),
+    { immediate: true, deep: true }
```
Comment (zzcr) [inline packages/renderless/src/tree-select/vue.ts:23]: 这里对数据进行深度监听，万一用户的数据量很多会不会造成性能问题呢？

Comment (zzcr) [reply packages/renderless/src/tree-select/vue.ts:23]: 这段代码是从select组件迁移的，后续如果遇到大数据场景再进行优化处理

**Review by zzcr — APPROVED** [review]
