### PR TITLE
fix(time-spinner): [time-spinner] fix startDate & endDate prop type issue when isRan…

### LINKED ISSUE #3295: 🐛 [Bug]:[Vue warn]: Invalid prop: type check failed for prop "startDate". Expected Object, got Date
### Version

2.21.0

### Vue Version

2.7.16

### Link to minimal reproduction

vue的dev版本，单独安装的time-picker组件，其子组件time-spinner的props中startDate、endDate源码中接收Object类型的

Image

，应该是Date | string | number

### Step to reproduce

使用time-picker，isRange为true

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

darkingtail

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by darkingtail**
…ge is true in time components (#3295)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- The TimeSpinner component now accepts a wider range of input types (Date, String, or Number) for start and end values.
	- Default values have been updated to an empty state, enhancing flexibility in configuring time inputs.

### CODE REVIEW

**Comment by zzcr** [comment]
[fix(time-spinner): [time-spinner] 你好可以用中括号触发下组件的e2e测试用例哈

File: packages/vue/src/time-spinner/src/index.ts [hunk 1]
```diff
@@ -42,12 +42,12 @@ export default defineComponent({
       }
     },
     startDate: {
-      type: Object,
-      default: () => ({})
+      type: [Date, String, Number],
```
Comment (discreted66) [inline packages/vue/src/time-spinner/src/index.ts]: 建议修改为[Object, Date, String, Number],

Comment (darkingtail) [reply packages/vue/src/time-spinner/src/index.ts]: 好的

**Review by zzcr — APPROVED** [review]
