### PR TITLE
fix(grid): [grid] fix repeated trigger cell active when boardConfig.isEdit is set true

### LINKED ISSUE #2321: 🐛 [Bug]: 表格组件设置了键盘设置以后，编辑表格的时候，只要不是输入汉字，比如直接输入数字，单元格的输入会自动选中输入的内容，导致后一次输入会覆盖前一次输入的内容
### Version

3.18.0

### Vue Version

3.4.29

### Link to minimal reproduction

<template>
  <tiny-grid
    :keyboard-config="keyboardConfigData"
    :data="tableData"
    seq-serial
    height="200"
    :edit-config="{ trigger: 'dblclick', mode: 'cell', showStatus: true }"
    :mouse-config="{ selected: true }"
  >
    <tiny-grid-column type="index" width="60"></tiny-grid-column>
    <tiny-grid-column field="name" title="名称" :editor="{ component: 'input', autoselect: true }"></tiny-grid-column>
    <tiny-grid-column field="area" title="区域" :editor="{ component: 'select', options }"></tiny-grid-column>
    <tiny-grid-column
      field="address"
      title="地址"
      :editor="{ component: 'input', autoselect: true }"
    ></tiny-grid-column>
    <tiny-grid-column
      field="introduction"
      title="公司简介"
      :editor="{ component: 'input', autoselect: true }"
      show-overflow="ellipsis"
    ></tiny-grid-column>
  </tiny-grid>
</template>

<script setup lang="jsx">
import { ref } from 'vue'
import { Grid as TinyGrid, GridColumn as TinyGridColumn, Modal } from '@opentiny/vue'

const keyboardConfigData = ref({
  isArrow: true, // 是否开启方向键功能，默认false
  isDel: true, // 是否开启删除键功能，默认false
  isTab: true, // 是否开启 Tab 键功能，默认false
  isEdit: true, // 是否开启任意键进入编辑（功能键除外），默认false
  editMethod({ seq }) {
    Modal.message({ message: `seq: ${seq}`, status: 'info' })
  }
})
const options = ref([
  { label: '华北区', value: '华北区' },
  { label: '华东区', value: '华东区' },
  { label: '华南区', value: '华南区' }
])
const tableData = ref([
  {
    id: '1',
    name: 'GFD科技YX公司',
    area: '华东区',
    address: '福州',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '2',
    name: 'WWWW科技YX公司',
    area: '华南区',
    address: '深圳福田区',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '3',
    name: 'RFV有限责任公司',
    area: '华南区',
    address: '中山市',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '4',
    name: 'TGBYX公司',
    area: '华北区',
    address: '梅州',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '5',
    name: 'YHN科技YX公司',
    area: '华南区',
    address: '韶关',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '6',
    name: '康康物业YX公司',
    area: '华北区',
    address: '广州天河区',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '7',
    name: '深圳市福德宝网络技术YX公司',
    area: '华南区',
    address: '清远',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '8',
    name: '西安门福德宝网络技术YX公司',
    area: '华东区',
    address: '厦门',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '9',
    name: 'WWWW科技股份有限子公司',
    area: '华南区',
    address: '韶关',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  },
  {
    id: '10',
    name: 'WSX科技YX公司',
    area: '华南区',
    address: '广州',
    introduction: '公司技术和研发实力雄厚，是国家863项目的参与者，并被政府认定为“高新技术企业”。'
  }
])
</script>

### Step to reproduce

编辑表格输入多个数字

### What is expected

表格显示输入的数字

### What is actually happening

后一次输入的数字覆盖了前一次输入的数字

### What is your project name

公司内部项目

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by gimmyhehe**
# PR
修复当配置了boardConfig.isEdit为true时，激活编辑被一直重复触发
PixPin_2025-01-09_17-32-36
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
close #2321 

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved cell editing behavior in the grid component
	- Enhanced keyboard interaction logic to prevent redundant edit actions
	- Refined cell selection and editing state management

### CODE REVIEW

File: packages/vue/src/grid/src/table/src/utils/handleGlobalKeydownEvent.ts [hunk 1]
```diff
@@ -147,7 +149,7 @@ export function onGlobalKeydown(event, _vm) {
     rule8({ isKeyDel, treeConfig, highlightCurrentRow, currentRow, isKeyBack, keyboardConfig, _vm, event, selected }),
     rule9({ keyboardConfig, isKeyWithCtrl, isKeyA, isKeyX, isKeyC, isKeyV, _vm, event }),
     // 如果是按下非功能键之外允许直接编辑
-    rule10({ keyboardConfig, isKeyWithCtrl, _vm, event, selected })
+    rule10({ keyboardConfig, isKeyWithCtrl, _vm, event, selected, actived })
```
Comment (zzcr) [inline packages/vue/src/grid/src/table/src/utils/handleGlobalKeydownEvent.ts:152]: 如果要发补丁版本，升级下版本号

**Review by zzcr — APPROVED** [review]
